language: java
dist: xenial

# The commands are in order how they are executed in a job lifecycle
# https://docs.travis-ci.com/user/job-lifecycle#the-job-lifecycle

script:
  - ./gradlew build

deploy:
  - provider: script
    on:
      condition: env(RELEASE_VERSION) =~ /^([0-9]|[1-9][0-9]*)\.([0-9]|[1-9][0-9]*)\.([0-9]|[1-9][0-9]*)$/
    script: echo $RELEASE_VERSION