language: java
dist: xenial

# The commands are in order how they are executed in a job lifecycle
# https://docs.travis-ci.com/user/job-lifecycle#the-job-lifecycle

script:
  - echo FAKE BUILD
  #- ./gradlew build

deploy:
  - provider: script
    skip_cleanup: true
    on:
      #condition: $RELEASE_VERSION =~ /^([0-9]|[1-9][0-9]*)\.([0-9]|[1-9][0-9]*)\.([0-9]|[1-9][0-9]*)$/
      condition: $RELEASE_VERSION != ''
    script: >-
      git remote set-url origin https://${GITHUB_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git &&
      git config --global user.email "${GITHUB_USER}" &&
      git config --global user.name "Travis CI" &&
      git checkout $TRAVIS_BRANCH &&
      ./gradlew release -Prelease.useAutomaticVersion=true -Prelease.releaseVersion=$RELEASE_VERSION
  - provider: releases
    api_key: $GITHUB_TOKEN
    skip_cleanup: true
    on:
      tags: true