language: java
dist: xenial

# The commands are in order how they are executed in a job lifecycle
# https://docs.travis-ci.com/user/job-lifecycle#the-job-lifecycle

env:
  - RELEASE_VERSION=1.1.0

script:
  - echo FAKE BUILD
  #- ./gradlew build

deploy:
  - provider: script
    on:
      #condition: $RELEASE_VERSION =~ /^([0-9]|[1-9][0-9]*)\.([0-9]|[1-9][0-9]*)\.([0-9]|[1-9][0-9]*)$/
      condition: $RELEASE_VERSION != ''
    script: |
      gradlew release -Prelease.useAutomaticVersion=true -Prelease.releaseVersion=$$RELEASE_VERSION
  - provider: script
    script: echo MOIN $RELEASE_VERSION